routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');

	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');

	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');

}); 

Route::namespace('Frontend')->prefix('member')->group(function(){
	Route::get('/trang-chu', 'MemberController@dashboard_page')->name('member.dashboard');
	Route::get('/cap-nhat-thong-tin', 'MemberController@information_page')->name('member.information');
	Route::get('/doi-mat-khau', 'MemberController@password_page')->name('member.password');
	Route::get('/doi-email', 'MemberController@email_page')->name('member.email');
	Route::get('/doi-email-buoc-2', 'MemberController@email_step_2_page')->name('member.email-step-2');
	Route::get('/don-hang', 'MemberController@order_page')->name('member.order');
	Route::get('/hoa-hong-cap-1', 'MemberController@aff_lv1_page')->name('member.affiliate-lv1');
	Route::get('/hoa-hong-cap-2', 'MemberController@aff_lv2_page')->name('member.affiliate-lv2');
	Route::get('/don-hang-hoa-hong-cap-1', 'MemberController@order_aff_lv1_page')->name('member.order-affiliate-lv1');
	Route::get('/don-hang-hoa-hong-cap-2', 'MemberController@order_aff_lv2_page')->name('member.order-affiliate-lv2');
	Route::get('/rut-tien', 'MemberController@aff_withdraw_page')->name('member.affiliate-withdraw');
	Route::get('/lich-su-rut-tien', 'MemberController@aff_withdraw_history_page')->name('member.affiliate-withdraw-history');
	Route::get('/thanh-toan-credit-aff/{id}', 'MemberController@payment_aff')->name('member.payment_aff');

	Route::post('/cap-nhat-thong-tin', 'MemberController@update_information')->name('member.update_information');
	Route::post('/doi-mat-khau', 'MemberController@change_password')->name('member.change_password');
	Route::post('/doi-email-buoc-1', 'MemberController@change_email_step_1')->name('member.change_email_step_1');
	Route::post('/doi-email-buoc-2', 'MemberController@change_email_step_2')->name('member.change_email_step_2');
	Route::post('/rut-tien', 'MemberController@aff_withdraw_credit')->name('member.aff_withdraw_credit');

});

Route::namespace('Admin')->group(function(){
	Route::get('logins','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('logins','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});



Route::namespace('Admin')->middleware('logins')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::resource('affiliates','AffiliatesController');
	Route::resource('affiliates-withdraw','AffiliatesWithdrawController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	Route::get('cauhinh-affiliates','CauhinhAffiliatesController@editAffiliatesNoId')->name('cauhinh-affiliates.editAffiliatesNoId');
	Route::put('cauhinh-affiliates','CauhinhAffiliatesController@updateAffiliatesNoId')->name('cauhinh-affiliates.updateAffiliatesNoId');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/DmspController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Dmsps\StoreRequest;
use App\Model\Dmsp;
use Illuminate\Support\Facades\Auth;
use Input;
use Illuminate\Database\QueryException;
use Carbon\Carbon;

class DmspController extends Controller
{
    private $dmsp;

    public function __construct(
                                Dmsp $dmsp
                                )
    {
        $this->dmsp          = $dmsp;
        
    }

    public function getParent()
    {
        $data = [];
        
        $optParent = $this->dmsp->listCateByIdParent(0); 
        foreach($optParent  as $oP)
        {
            $dataOptPar = array('id'     => $oP->id, 
                                'name'   => $oP->name);
            array_push($data, $dataOptPar);

            $optChild = $this->dmsp->listCateByIdParent($oP->id);
            foreach ($optChild as $oC) 
            {
                // Tạo mảng 2 chiều danh mục con
                $dataOptChi= [
                                "id"=>$oC->id,
                                "name"=>"-- ".$oC->name
                             ];
                array_push($data, $dataOptChi);
            }
            
        }
        return $data;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['dmsp']   = $this->dmsp->index();
        $data['optArr'] = $this->getParent();
        return view('admin.module.dmsps.dmsp-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $data['optArr'] = $this->getParent();

        return view('admin.module.dmsps.dmsp-create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {
        $menu    = $this->dmsp->getId();
        if(count($menu) < 9)
        {
            $data = array(
                            'name' => $req->name,
                            'alias' => (empty($req->alias)) ? chuyen($req->name) : $req->alias,
                            'vitri' => $req->vitri,
                            'id_parent' => $req->id_parent,
                            'created_at' => Carbon::now('Asia/Ho_Chi_Minh')
                        );
            try {
                 $this->dmsp->storeDmsp($data);
            }catch (QueryException $exception) {
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
        elseif($req->id_parent == 0)
        {
            $data = array(
                            'name' => $req->name,
                            'alias' => (empty($req->alias)) ? chuyen($req->name) : $req->alias,
                            'vitri' => $req->vitri,
                            'id_parent' => $req->id_parent,
                            'created_at' => Carbon::now('Asia/Ho_Chi_Minh')
                        );
            try {
                 $this->dmsp->storeDmsp($data);
            }catch (QueryException $exception) {
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
        else
        {
            return redirect()->back()->with('alerterr','Danh mục con đã đạt số lượng tối đa');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['optArr'] = $this->getParent();

        $data['dmsp'] = $this->dmsp->getDmsp($id);
        return view('admin.module.dmsps.dmsp-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        if (isset($_POST['addTintuc']))
        {
            $data = array(
                        'name' => $req->name,
                        'alias' => (empty($req->alias)) ? chuyen($req->name) : $req->alias,
                        'vitri' => $req->vitri,
                        'id_parent' => $req->id_parent,
                    );
            try {
                $this->dmsp->updateDmsp($data,$id);
            }catch (QueryException $exception) {
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Sửa thành công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                $this->dmsp->destroyDmsp($id);
            }
            return redirect()->route('dmsp.index')->with('alertsuc','Xóa thành công');
        }
    }
}

resources/views/admin/module/dmsps/dmsp-create.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('dmsp.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Thêm</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.btn_them')}}</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{ route('dmsp.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                             <span class="input-group-addon">Tên danh mục</span>
                                            <input value="{{old('name')}}" type="text" name="name" class="form-control" placeholder="Tên danh mục">
                        </div>
                        <div class="col-sm-6">
                             <span class="input-group-addon">Alias</span>
                                            <input value="{{old('alias')}}" type="text" name="alias" class="form-control" placeholder="Alias">
                        </div>
                    </div>
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                             <span class="input-group-addon">Danh mục</span>
                                        <select name="id_parent" class="form-control pro-edt-select form-control-primary">
                                            <option value="0">Không chọn loại</option>
                                            @for($i = 0; $i < count($optArr); $i++)
                                                <option value="{{$optArr[$i]['id']}}">{!!$optArr[$i]['name']!!}</option>
                                            @endfor
                                        </select>
                        </div>
                        <div class="col-sm-6">
                            <span class="input-group-addon ">Vị trí</span>
                                        <input value="0" value="{{old('vitri')}}" type="text" name="vitri" class="form-control" placeholder="Vị trí">
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/dmsps/dmsp-edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('dmsp.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Sửa</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.btn_sua')}}</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{ route('dmsp.update', ['dmsp' => $dmsp->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                             <span class="input-group-addon">Tên danh mục</span>
                                            <input value="{{old('title',$dmsp->name)}}" type="text" name="name" class="form-control" placeholder="Tên danh mục ">
                        </div>
                        <div class="col-sm-6">
                             <span class="input-group-addon">Alias</span>
                                           <input value="{{old('alias',$dmsp->alias)}}" type="text" name="alias" class="form-control" placeholder="Alias">
                        </div>
                    </div>
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <span class="input-group-addon">Danh mục</span>
                                <select name="id_parent" class="form-control pro-edt-select form-control-primary">
                                <option value="">Please Choose Category</option>
                                @if($dmsp->id_parent == 0)
                                    @for($i = 0; $i < count($optArr); $i++)
                                    <option value="{!!$optArr[$i]['id']!!}" {{ $dmsp->id == $optArr[$i]['id'] ? "selected" : "" }}>{!!$optArr[$i]['name']!!}</option>
                                    @endfor
                                @else
                                @for($i = 0; $i < count($optArr); $i++)
                                    <option value="{!!$optArr[$i]['id']!!}" {{ $dmsp->id_parent == $optArr[$i]['id'] ? "selected" : "" }}>{!!$optArr[$i]['name']!!}</option>
                                @endfor
                                @endif
                            </select>
                        </div>
                        <div class="col-sm-6">
                            <span class="input-group-addon ">Vị trí</span>
                            <input value="{{old('vitri',$dmsp->vitri)}}" type="text" name="vitri" class="form-control" placeholder="Vị trí">
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="addTintuc" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/dmsps/dmsp-list.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('dmsp.index')}}" class="breadcrumb-item">Danh sách</a>

            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.danhmuc_sanpham')}}</h5>
                 
            </div>
            <div class="card-body">
                <div class="product-status-wrap">
                    <div class="form-group">
                         <a  class="btn btn-success" href="{{ route('dmsp.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                     <tr>
                                        <td>
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </td>
                                        <th>Tên danh mục</th>
                                        <th>Vị trí</th>
                                        <th>Danh mục</th>
                                        <th>Cập nhật</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($dmsp as $item)
                                        <tr style="vertical-align: top">
                                            <td>
                                                <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                            </td>
                                            <td style="width: 32%">{{$item->name}}</td>
                                            <td style="width: 20%">{{$item->vitri}}</td>
                                            <td style="width: 35%">
                                                    @if(empty($item->id_parent))
                                                    {{$item->name}}
                                                    @else
                                                        @foreach($optArr as $opt)
                                                            @if($opt['id'] == $item->id_parent)
                                                                {{$opt['name']}}
                                                            @endif
                                                        @endforeach
                                                    @endif 
                                           </select>
                                            </td>
                                            <td style="width: 10%;text-align: center;">
                                                <a href="{{ route('dmsp.edit', ['dmsp' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                                </a>
                                            </td>                   
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group row">
                            {{-- <div class="col-sm-6"> --}}
                                {{ method_field('DELETE') }}
                                <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="btn btn-danger">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            {{-- </div> --}}
                            <div style="position: absolute;right: 20px">
                                {{$dmsp->links()}}
                            </div>
                        </div>
                    
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div> 
@endsection