routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');

	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');

	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');

}); 

Route::namespace('Frontend')->prefix('member')->group(function(){
	Route::get('/trang-chu', 'MemberController@dashboard_page')->name('member.dashboard');
	Route::get('/cap-nhat-thong-tin', 'MemberController@information_page')->name('member.information');
	Route::get('/doi-mat-khau', 'MemberController@password_page')->name('member.password');
	Route::get('/doi-email', 'MemberController@email_page')->name('member.email');
	Route::get('/doi-email-buoc-2', 'MemberController@email_step_2_page')->name('member.email-step-2');
	Route::get('/don-hang', 'MemberController@order_page')->name('member.order');
	Route::get('/hoa-hong-cap-1', 'MemberController@aff_lv1_page')->name('member.affiliate-lv1');
	Route::get('/hoa-hong-cap-2', 'MemberController@aff_lv2_page')->name('member.affiliate-lv2');
	Route::get('/don-hang-hoa-hong-cap-1', 'MemberController@order_aff_lv1_page')->name('member.order-affiliate-lv1');
	Route::get('/don-hang-hoa-hong-cap-2', 'MemberController@order_aff_lv2_page')->name('member.order-affiliate-lv2');
	Route::get('/rut-tien', 'MemberController@aff_withdraw_page')->name('member.affiliate-withdraw');
	Route::get('/lich-su-rut-tien', 'MemberController@aff_withdraw_history_page')->name('member.affiliate-withdraw-history');
	Route::get('/thanh-toan-credit-aff/{id}', 'MemberController@payment_aff')->name('member.payment_aff');

	Route::post('/cap-nhat-thong-tin', 'MemberController@update_information')->name('member.update_information');
	Route::post('/doi-mat-khau', 'MemberController@change_password')->name('member.change_password');
	Route::post('/doi-email-buoc-1', 'MemberController@change_email_step_1')->name('member.change_email_step_1');
	Route::post('/doi-email-buoc-2', 'MemberController@change_email_step_2')->name('member.change_email_step_2');
	Route::post('/rut-tien', 'MemberController@aff_withdraw_credit')->name('member.aff_withdraw_credit');

});

Route::namespace('Admin')->group(function(){
	Route::get('logins','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('logins','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});



Route::namespace('Admin')->middleware('logins')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::resource('affiliates','AffiliatesController');
	Route::resource('affiliates-withdraw','AffiliatesWithdrawController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	Route::get('cauhinh-affiliates','CauhinhAffiliatesController@editAffiliatesNoId')->name('cauhinh-affiliates.editAffiliatesNoId');
	Route::put('cauhinh-affiliates','CauhinhAffiliatesController@updateAffiliatesNoId')->name('cauhinh-affiliates.updateAffiliatesNoId');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/UseradminController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Requests\Useradmins\StoreRequest;
use App\Http\Controllers\Controller;
use App\Model\Useradmin;
use Input;
use Carbon\Carbon;

class UseradminController extends Controller
{
    private $useradmin;


    public function __construct(Useradmin $useradmin)
    {
        $this->useradmin          = $useradmin;

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['useradmin']   = $this->useradmin->index();
        return view('admin.module.useradmin.user-list',$data);    
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('admin.module.useradmin.user-create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {
        $data = array(
                        'username' => $req->username,
                        'password' => bcrypt($req->password),
                        'rule' => $req->rule,
                        'fullname' => $req->fullname,
                        'phone' => $req->phone,
                        'email' =>$req->email,
                        'created_at'=> Carbon::now('Asia/Ho_Chi_Minh')
                    ); 
                
        $this->useradmin->store($data);
        return redirect()->back()->with('alertsuc','Thêm useradmin thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['useradmin'] = $this->useradmin->getUser($id);
        return view('admin.module.useradmin.user-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        $data = array(
                        'rule' => $req->rule,
                        'fullname' => $req->fullname,
                        'phone' => $req->phone,
                        'email' =>$req->email,
                    ); 
                
        $this->useradmin->updateUser($data,$id);
        return redirect()->back()->with('alertsuc','Sửa useradmin thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                if($id > 1)
                {
                    $this->useradmin->destroyUser($id);
                }
                else
                {
                    return redirect()->back()->with('alerterr','Vui lòng không xóa admin tổng');
                }
            }
            return redirect()->route('useradmin.index')->with('alertsuc','Xóa user thành công');
        }

    }
}

resources/views/admin/module/useradmin/user-create.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Thêm</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Thông tin quản trị viên</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{ route('useradmin.store') }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Họ tên *</label>
                            <input value="{{old('fullname')}}" type="text" name="fullname" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Số điện thoại *</label>
                            <input value="{{old('phone')}}" type="text" name="phone" class="form-control"  >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Email *</label>
                            <input value="{{old('email')}}" type="text" name="email" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Tên đăng nhập *</label>
                            <input value="{{old('username')}}" type="text" name="username" class="form-control">
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Mật khẩu *</label>
                            <input value="{{old('password')}}" type="password" name="password" class="form-control">
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Quyền *</label>
                            <select name="rule" class="form-control pro-edt-select form-control-primary">
                                <option value='0' selected="">Admin tổng</option>
                                    <option value='1'>Admin post</option>
                                    <option value='2'>Admin product</option>
                                    <option value='3'>Admin cấp 3</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/useradmin/user-edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Sửa</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Cập nhật quản trị viên</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{route('useradmin.update', ['sanpham' => $useradmin->id]) }}" method="POST" enctype="multipart/form-data">
                @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Họ tên *</label>
                            <input value="{{old('fullname',$useradmin->fullname)}}" type="text" name="fullname" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Số điện thoại *</label>
                            <input value="{{old('phone',$useradmin->phone)}}" type="text" name="phone" class="form-control"  >
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Email *</label>
                            <input value="{{old('email',$useradmin->email)}}" type="text" name="email" class="form-control" >
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Tên đăng nhập *</label>
                            <input value="{{old('username',$useradmin->username)}}" type="text" name="username" class="form-control">
                        </div>
                    </div>
                     <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <label class="lable_edit">Mật khẩu *</label>
                            <input value="{{old('password')}}" type="password" name="password" class="form-control">
                        </div>
                        <div class="col-sm-6">
                            <label class="lable_edit">Quyền *</label>
                            <select name="rule" class="form-control pro-edt-select form-control-primary">
                                <option value='0' {{$useradmin->rule == 0 ? 'selected' : ''}}>Admin</option>
                                <option value='1' {{$useradmin->rule == 1 ? 'selected' : ''}}>Admin post</option>
                                <option value='2' {{$useradmin->rule == 2 ? 'selected' : ''}}>Admin product</option>
                                <option value='3' {{$useradmin->rule == 3 ? 'selected' : ''}}>Admin cấp 3</option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                       {{ method_field('PUT') }}
                        <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                            </button>
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>


@endsection

resources/views/admin/module/useradmin/user-list.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('useradmin.index')}}" class="breadcrumb-item">Danh sách</a>
                {{-- <span class="breadcrumb-item active">Current</span> --}}
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')
<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.danhsach_admin')}}</h5>
                 
            </div>
            <div class="card-body">
                <div class="product-status-wrap">
                    <div class="form-group">
                        <a class="btn btn-success" href="{{ route('useradmin.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                    <tr >
                                        <th scope="col">
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </th>
                                        <th scope="col">Mã</th>
                                        <th scope="col">Họ tên</th>
                                        <th scope="col">Username</th>
                                        <th scope="col">Quyền</th>
                                        <th scope="col">Phone</th>
                                        <th scope="col">Email</th>
                                        <th scope="col">Hoạt động</th>
                                        <th scope="col">Cập nhật</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($useradmin as $item)
                                    <tr>
                                        <td >
                                            <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                        </td>
                                        <td>{{$item->id}}</td>
                                        <td>{{$item->fullname}}</td>
                                        <td>{{$item->username}}</td>
                                        <td>
                                            @if($item->rule==0)
                                                Admin
                                            @elseif($item->rule==1)
                                                Admin post
                                            @elseif($item->rule==2)
                                                Admin product
                                            @elseif($item->rule==3)
                                                Admin cấp 3
                                            @endif
                                        </td>
                                        <td>{{$item->phone}}</td>
                                        <td>{{$item->email}}</td>
                                        <td>
                                                {{convertdate1($item->created_at)}}
                                        </td>
                                        <td style="text-align: center;">
                                            <a href="{{ route('useradmin.edit', ['useradmin' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                            </a>
                                        </td>                   
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            {{ method_field('DELETE') }}
                            <button onClick="return xacnhan('Bạn có chắc chắn muốn xóa ?');" type="submit" id="btnXoaList" name="btnXoaList" class="btn btn-danger">
                            <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                        </div>
                    
                    </form>
                     {{$useradmin->links()}}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection