routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');

	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');

	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');

}); 

Route::namespace('Frontend')->prefix('member')->group(function(){
	Route::get('/trang-chu', 'MemberController@dashboard_page')->name('member.dashboard');
	Route::get('/cap-nhat-thong-tin', 'MemberController@information_page')->name('member.information');
	Route::get('/doi-mat-khau', 'MemberController@password_page')->name('member.password');
	Route::get('/doi-email', 'MemberController@email_page')->name('member.email');
	Route::get('/doi-email-buoc-2', 'MemberController@email_step_2_page')->name('member.email-step-2');
	Route::get('/don-hang', 'MemberController@order_page')->name('member.order');
	Route::get('/hoa-hong-cap-1', 'MemberController@aff_lv1_page')->name('member.affiliate-lv1');
	Route::get('/hoa-hong-cap-2', 'MemberController@aff_lv2_page')->name('member.affiliate-lv2');
	Route::get('/don-hang-hoa-hong-cap-1', 'MemberController@order_aff_lv1_page')->name('member.order-affiliate-lv1');
	Route::get('/don-hang-hoa-hong-cap-2', 'MemberController@order_aff_lv2_page')->name('member.order-affiliate-lv2');
	Route::get('/rut-tien', 'MemberController@aff_withdraw_page')->name('member.affiliate-withdraw');
	Route::get('/lich-su-rut-tien', 'MemberController@aff_withdraw_history_page')->name('member.affiliate-withdraw-history');
	Route::get('/thanh-toan-credit-aff/{id}', 'MemberController@payment_aff')->name('member.payment_aff');

	Route::post('/cap-nhat-thong-tin', 'MemberController@update_information')->name('member.update_information');
	Route::post('/doi-mat-khau', 'MemberController@change_password')->name('member.change_password');
	Route::post('/doi-email-buoc-1', 'MemberController@change_email_step_1')->name('member.change_email_step_1');
	Route::post('/doi-email-buoc-2', 'MemberController@change_email_step_2')->name('member.change_email_step_2');
	Route::post('/rut-tien', 'MemberController@aff_withdraw_credit')->name('member.aff_withdraw_credit');

});

Route::namespace('Admin')->group(function(){
	Route::get('logins','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('logins','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});



Route::namespace('Admin')->middleware('logins')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::resource('affiliates','AffiliatesController');
	Route::resource('affiliates-withdraw','AffiliatesWithdrawController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	Route::get('cauhinh-affiliates','CauhinhAffiliatesController@editAffiliatesNoId')->name('cauhinh-affiliates.editAffiliatesNoId');
	Route::put('cauhinh-affiliates','CauhinhAffiliatesController@updateAffiliatesNoId')->name('cauhinh-affiliates.updateAffiliatesNoId');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/NhanxetController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Nhanxets\StoreRequest;
use App\Model\Nhanxet;
use DB;
use Input;
use File;
use Carbon\Carbon;
class NhanxetController extends Controller
{
    private $nhanxet;

    public function __construct(Nhanxet $nhanxet)
    {
        $this->nhanxet          = $nhanxet;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['nhanxet']   = $this->nhanxet->index();
        return view('admin.module.nhanxets.nhanxet-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.module.nhanxets.nhanxet-create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {

        $data = array(
                        'fullname' => $req->fullname,
                        'content' => $req->content,
                        'created_at' => Carbon::now('Asia/Ho_Chi_Minh')
                    );

        if($req->hasFile('photos')) 
        {
            //Quy dinh duoi
            $allowedfileExtension=['jpeg', 'jpg', 'png', 'gif'];
            //Lay image
            $file = $req->file('photos');
            //Lay duoi image
            $extension = strtolower($file->getClientOriginalExtension());
            //Kiem tra duoi co trong quy dinh khong
            $check=in_array($extension,$allowedfileExtension);
            if($check) {
                //upload tung image
                $filename = $req->photos->store('nhanxet');
                $data['img'] = $filename;
                $this->nhanxet->storeNhanxet($data);
                return redirect()->back()->with('alertsuc','Thêm thành công');
            }
            else
            {
                return redirect()->back()->with('alerterr','Vui lòng chọn đúng định dạng ảnh');
            }
        }
        else
        {
            $this->nhanxet->storeNhanxet($data);
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['nhanxet'] = $this->nhanxet->getNhanxet($id);
        return view('admin.module.nhanxets.nhanxet-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        if (isset($_POST['addTintuc']))
        {
            $data = array(
                        'fullname' => $req->fullname,
                        'content' => $req->content,
                    );
            if($req->hasFile('photos')) 
            {
            //     //Quy dinh duoi
                $allowedfileExtension=['jpeg', 'jpg', 'png', 'gif'];
                //Lay image
                $file = $req->file('photos');
                //Lay duoi image
                $extension = strtolower($file->getClientOriginalExtension());
                //Kiem tra duoi co trong quy dinh khong
                $check=in_array($extension,$allowedfileExtension);
                if($check) {
                    //upload tung image
                    $this->nhanxet->destroyImg($id);
                    $filename = $req->photos->store('nhanxet');
                    $data['img'] = $filename;
                    $this->nhanxet->updateNhanxet($data,$id);
                    return redirect()->back()->with('alertsuc','Sửa thành công');
                }
                else
                {
                    return redirect()->back()->with('alerterr','Vui lòng chọn đúng định dạng ảnh');
                }
            }
            $this->nhanxet->updateNhanxet($data,$id);
            return redirect()->back()->with('alertsuc','Sửa thành công');
        
        }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                $this->slide->destroyImg($id);
                $this->slide->destroyNhanxet($id);
            }
            return redirect()->route('nhanxet.index')->with('alertsuc','Xóa thành công');
        }

    }
}

resources/views/admin/module/nhanxets/nhanxet-create.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('nhanxet.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Thêm</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.btn_sua')}}</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{ route('nhanxet.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="col-sm-12 row">
                        <div class="col-sm-6 form-group">
                           <span class="input-group-addon">Họ tên</span>
                           <input value="{{old('fullname')}}" type="text" name="fullname" class="form-control" placeholder="Nhập họ tên">
                        </div>
                        <div class="col-sm-6 form-group">
                           <span class="input-group-addon ">Hình ảnh</span>
                                <input type="file" name="photos" class="btn btn-primary  ">
                        </div>
                    </div>
                    <div class="col-sm-12 form-group">
                        <span>Nội Dung</span>
                        <textarea rows="10" id="editor1" name="content" placeholder="Type the content here!" >
                           
                        </textarea>
                    </div>
                    <div class="form-group">
                        <button name="addTintuc" name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/nhanxets/nhanxet-edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('nhanxet.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Sửa</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.btn_sua')}}</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{ route('nhanxet.update', ['nhanxet' => $nhanxet->id]) }}" method="POST" enctype="multipart/form-data">
    @csrf
    {{ method_field('PUT') }}
                    <div class="col-sm-12 border-bottom row form-group" style="padding-bottom: 5px">
                        <div class="col-sm-6 form-group">
                            <label>Hình ảnh tin tức</label>  
                            @if($nhanxet->img == "product_default.jpg")
                                Không có hình ảnh
                            @else
                            <div class="row">
                                @php $arr_img = explode("||",$nhanxet->img);@endphp
                                @for($i=0 ; $i<count($arr_img) ; $i++)
                                 <img style="width: 95px;height: 95px;padding: 5px;margin-right: 10px" class="form-control" src="{{ asset('image/'.$nhanxet->img) }}" alt="">
                                @endfor
                                {{-- <button style="height: 35px" class="btn btn-danger" type="submit" title="Xóa ảnh" name="xoaEdit"> <i class="fa fa-trash-o" aria-hidden="true"></i></button> --}}
                                @endif
                            </div>
                           
                        </div>
                        <div class="col-sm-6 form-group">
                            <label>Chọn hình ảnh</label>
                            <input type="file" name="photos[]" multiple="" class="btn btn-primary  ">
                            <input type="hidden" name="hinhcu" value="{{$nhanxet->img}}">
                        </div>
                   
                    </div>
                    <div class="col-sm-6 form-group row">
                       <span class="input-group-addon">Họ tên</span>
                       <input value="{{old('fullname',$nhanxet->fullname)}}" type="text" name="fullname" class="form-control" placeholder="Nhập họ tên">
                    </div>
                    <div class="col-sm-12 form-group">
                        <span>Nội Dung</span>
                        <textarea rows="10" id="editor1" name="content" placeholder="Type the content here!" >
                            {{$nhanxet->content}}
                        </textarea>
                    </div>
                    <div class="form-group">
                        <button name="addTintuc" name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/nhanxets/nhanxet-list.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('nhanxet.index')}}" class="breadcrumb-item">Danh sách</a>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.danhsach_nhanxet')}}</h5>
                 
            </div>
            <div class="card-body">
                <div class="product-status-wrap">
                    <div class="form-group">
                         <a  class="btn btn-success" href="{{ route('nhanxet.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </td>
                                        <th>Họ tên</th>
                                        <th>Hình ảnh</th>
                                        <th>Nội dung</th>
                                        <th>Cập nhật</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($nhanxet as $item)
                                        <tr>
                                            <td >
                                                <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                            </td>
                                            <td style="width: 25%">{{$item->fullname}}</td>
                                            <td style="width: 10%">
                                                <img style="width: 90px" src="{{ asset('image/'.$item->img) }}" alt="">
                                            </td>
                                            <td style="width: 55%">{{$item->content}}</td>
                                            <td style="width: 10%;text-align: center;">
                                                <a href="{{ route('nhanxet.edit', ['nhanxet' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                                    <i class="fa fa-pencil-square-o clear" aria-hidden="true"></i>
                                                </a>
                                            </td>                   
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            {{ method_field('DELETE') }}
                           <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="btn btn-danger">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                        </div>
                    
                    </form>
                     {{$nhanxet->links()}}
                </div>
            </div>
        </div>
    </div>
</div> 
@endsection