routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('Frontend')->group(function(){
	Route::get('/','HomeController@index')->name('trangchu.index');
	Route::get('trang-chu','HomeController@index')->name('trangchu.index');
	Route::get('danh-muc-san-pham/{alias}','HomeController@getPages')->name('trangchu.getPages');
	Route::get('danh-muc-nho/{alias}','HomeController@getPagesCon')->name('trangchu.getPagesCon');
	Route::get('chi-tiet-san-pham/{alias}','HomeController@getDetail')->name('trangchu.detail');
	Route::get('chi-tiet-tin-tuc/{alias}','HomeController@getTintucDetail')->name('trangchu.tintucdetail');
	Route::get('gioi-thieu','HomeController@Gioithieu')->name('trangchu.gioithieu');
	Route::get('lien-he','HomeController@Lienhe')->name('trangchu.lienhe');
	Route::post('lien-he/create','HomeController@store')->name('trangchu.store');

	Route::get('trang-chu/dang-nhap','LoginController@getLogin')->name('trangchu.getLogin');
	Route::post('trang-chu/dang-nhap','LoginController@postLogin')->name('trangchu.postLogin');
	Route::get('trang-chu/dang-ky','LoginController@getRegister')->name('trangchu.getRegister');
	Route::post('trang-chu/dang-ky','LoginController@postRegister')->name('trangchu.postRegister');
	Route::get('dang-xuat','LoginController@getLogout')->name('trangchu.getLogout');
	Route::get('dang-xuat2','LoginController@getLogout2')->name('trangchu.getLogout2');
	Route::get('thong-tin-ca-nhan', 'LoginController@getInformation')->name('trangchu.getInformation');
	Route::get('thay-doi-dia-chi', 'LoginController@getAddress')->name('trangchu.getAddress');

	Route::get('tim-mat-khau', 'ResetPasswordController@getTimMatKhau')->name('trangchu.getTimMatKhau');
	Route::post('tim-mat-khau', 'ResetPasswordController@sendEmail')->name('trangchu.sendEmail');
	Route::get('mat-khau-moi', 'ResetPasswordController@getNewPassword')->name('trangchu.getNewPassword');
	Route::post('mat-khau-moi', 'ResetPasswordController@postNewPassword')->name('trangchu.postNewPassword');

	Route::get('them-san-pham/{id}','ShoppingCartController@addProductToCart')->name('get.add.product');
	Route::get('gio-hang-cua-ban','ShoppingCartController@listCartProduct')->name('get.list.cart');
	Route::get('so-luong','ShoppingCartController@updownQtyProduct')->name('updown.product');
	Route::get('xoa-san-pham/{id}','ShoppingCartController@detroyProductCart')->name('get.delete.product');
	Route::get('xoa-tat-ca','ShoppingCartController@detroyAllProductCart')->name('get.delete.all.product');
	Route::get('xem-lai-hoa-don', 'ShoppingCartController@getRepostCart')->name('get.RepostCart');
	Route::get('dat-hang', 'ShoppingCartController@getDathang')->name('get.Dathang');
	Route::post('dat-hang', 'ShoppingCartController@postDathang')->name('post.Dathang');
	Route::get('/datacart', 'ShoppingCartController@getCart');

}); 

Route::namespace('Frontend')->prefix('member')->group(function(){
	Route::get('/trang-chu', 'MemberController@dashboard_page')->name('member.dashboard');
	Route::get('/cap-nhat-thong-tin', 'MemberController@information_page')->name('member.information');
	Route::get('/doi-mat-khau', 'MemberController@password_page')->name('member.password');
	Route::get('/doi-email', 'MemberController@email_page')->name('member.email');
	Route::get('/doi-email-buoc-2', 'MemberController@email_step_2_page')->name('member.email-step-2');
	Route::get('/don-hang', 'MemberController@order_page')->name('member.order');
	Route::get('/hoa-hong-cap-1', 'MemberController@aff_lv1_page')->name('member.affiliate-lv1');
	Route::get('/hoa-hong-cap-2', 'MemberController@aff_lv2_page')->name('member.affiliate-lv2');
	Route::get('/don-hang-hoa-hong-cap-1', 'MemberController@order_aff_lv1_page')->name('member.order-affiliate-lv1');
	Route::get('/don-hang-hoa-hong-cap-2', 'MemberController@order_aff_lv2_page')->name('member.order-affiliate-lv2');
	Route::get('/rut-tien', 'MemberController@aff_withdraw_page')->name('member.affiliate-withdraw');
	Route::get('/lich-su-rut-tien', 'MemberController@aff_withdraw_history_page')->name('member.affiliate-withdraw-history');
	Route::get('/thanh-toan-credit-aff/{id}', 'MemberController@payment_aff')->name('member.payment_aff');

	Route::post('/cap-nhat-thong-tin', 'MemberController@update_information')->name('member.update_information');
	Route::post('/doi-mat-khau', 'MemberController@change_password')->name('member.change_password');
	Route::post('/doi-email-buoc-1', 'MemberController@change_email_step_1')->name('member.change_email_step_1');
	Route::post('/doi-email-buoc-2', 'MemberController@change_email_step_2')->name('member.change_email_step_2');
	Route::post('/rut-tien', 'MemberController@aff_withdraw_credit')->name('member.aff_withdraw_credit');

});

Route::namespace('Admin')->group(function(){
	Route::get('logins','LoginController@getLogin')->middleware('loginal')->name('admin.getLogin');
	Route::post('logins','LoginController@postLogin')->name('admin.postLogin');;
	Route::get('logout','LoginController@getLogout')->name('admin.getLogout');
});



Route::namespace('Admin')->middleware('logins')->prefix('admin')->group(function(){
	Route::resource('/','HomeController');
	Route::resource('sanpham','SanphamController');
	Route::resource('useradmin','UseradminController');
	Route::resource('member','MemberController');
	Route::resource('tintuc','TintucController');
	Route::resource('dmtt','DmttController');
	Route::resource('dmsp','DmspController');
	Route::resource('slide','SlideController');
	Route::resource('nhanxet','NhanxetController');
	Route::resource('coupon','CouponController');
	Route::resource('hinhthuc','HinhthucController');
	Route::resource('cauhinh','CauhinhController');
	Route::resource('lienhe','LienheController');
	Route::resource('vanchuyen','VanchuyenController');
	Route::resource('donhang','DonhangController');
	Route::resource('affiliates','AffiliatesController');
	Route::resource('affiliates-withdraw','AffiliatesWithdrawController');
	Route::get('cauhinh','CauhinhController@editNoId')->name('cauhinh.editNoId');
	Route::put('cauhinh','CauhinhController@updateNoId')->name('cauhinh.updateNoId');
	Route::get('in-hoa-don','DonhangController@getInhoadon')->name('hoadon.getInhoadon');
	Route::post('updatedata','DonhangController@updatedata');
	Route::get('cauhinh-affiliates','CauhinhAffiliatesController@editAffiliatesNoId')->name('cauhinh-affiliates.editAffiliatesNoId');
	Route::put('cauhinh-affiliates','CauhinhAffiliatesController@updateAffiliatesNoId')->name('cauhinh-affiliates.updateAffiliatesNoId');
	// Route::post('/update_data/{id}', 'DonhangController@update_data')->name('donhang.update_data');

});

app/Http/Controllers/Admin/TintucController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Tintucs\StoreRequest;
use App\Model\Tintuc;
use App\Model\Dmtt;
use Illuminate\Support\Facades\Auth;
use DB;
use Input;
use File;
use Carbon\Carbon;

class TintucController extends Controller
{
    private $tintuc;
    private $dmtt;

    public function __construct(
                                Tintuc $tintuc,
                                Dmtt $dmtt
                                )
    {
        $this->tintuc          = $tintuc;
        $this->dmtt            = $dmtt;
        
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['dmtt'] = $this->dmtt->getParent();
        $data['tintuc']   = $this->tintuc->index();
        return view('admin.module.tintucs.tintuc-list',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['dmtt'] = $this->dmtt->getParent();
        return view('admin.module.tintucs.tintuc-create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreRequest $req)
    {

        $data = array(
                        'title' => $req->title,
                        'alias' => (empty($req->alias)) ? chuyen($req->title) : $req->alias,
                        'category' => $req->category,
                        'intro' => $req->intro,
                        'content' => $req->content,
                        'img' => $req->img,
                        'id_admin' => Auth::user()->id,
                        'created_at' => Carbon::now('Asia/Ho_Chi_Minh')
                    );
        if($req->hasFile('photos')) 
        {
            //Quy dinh duoi
            $allowedfileExtension=['jpeg', 'jpg', 'png', 'gif'];
            //Lay image
            $files = $req->file('photos');
            $exe_flg = true;
            foreach($files as $file) {
                //Lay duoi image
                $extension = strtolower($file->getClientOriginalExtension());
                //Kiem tra duoi co trong quy dinh khong
                $check=in_array($extension,$allowedfileExtension);
                
                if(!$check) {
                    $exe_flg = false;
                    return redirect()->back()->with('alerterr','Vui lòng chọn đúng định dạng ảnh');
                    break;
                }
            }
            if($exe_flg) {
                //upload tung image
                $arr = [];
                $errMsg1="";
                foreach ($req->photos as $photo) 
                {
                    $filename = $photo->store('tintuc');
                    array_push($arr, $filename);
                }
                if (!empty($arr)) 
                {
                    for ($i = 0; $i<count($arr); $i++) 
                    {
                    if($i + 1 == count($arr))
                        $errMsg1 .= $arr[$i]; 
                    else 
                        $errMsg1 .= $arr[$i]."||"; 
                    }
                }
                else 
                {
                        $errMsg1 = "NULL";
                } 
            $data['img'] = $errMsg1;
            try{
                $this->tintuc->store($data);
            }
            catch(QueryException $e){
                return back()->with('alerterr','Sai định dạng');
            }
            return redirect()->back()->with('alertsuc','Thêm thành công');
            }  
        }
        else
        {
            $data['img'] = "product_default.jpg";
            $this->tintuc->store($data);
            return redirect()->back()->with('alertsuc','Thêm thành công');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['dmtt'] = $this->dmtt->getParent();
        $data['tintuc'] = $this->tintuc->getTintuc($id);
        return view('admin.module.tintucs.tintuc-edit',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $req, $id)
    {
        if (isset($_POST['addTintuc']))
        {
            $data = array(
                        'title' => $req->title,
                        'alias' => (empty($req->alias)) ? chuyen($req->title) : $req->alias,
                        'category' => $req->category,
                        'intro' => $req->intro,
                        'content' => $req->content,
                        // 'img' => $req->img,
                        'id_admin' => Auth::user()->id
                    );
            if($req->hasFile('photos')) 
            {
                //Quy dinh duoi
                $allowedfileExtension=['jpeg', 'jpg', 'png', 'gif'];
                //Lay image
                $files = $req->file('photos');
                $exe_flg = true;
                foreach($files as $file) {
                    //Lay duoi image
                    $extension = strtolower($file->getClientOriginalExtension());
                    //Kiem tra duoi co trong quy dinh khong
                    $check=in_array($extension,$allowedfileExtension);
                    
                    if(!$check) {
                        $exe_flg = false;
                        return redirect()->back()->with('alerterr','Vui lòng chọn đúng định dạng ảnh');
                        break;
                    }
                }
                if($exe_flg) {
                    //upload tung image
                    $arr = [];
                    $errMsg1="";
                    foreach ($req->photos as $photo) 
                    {
                        $filename = $photo->store('tintuc');
                        array_push($arr, $filename);
                    }
                    if (!empty($arr)) 
                    {
                        for ($i = 0; $i<count($arr); $i++) 
                        {
                        if($i + 1 == count($arr))
                            $errMsg1 .= $arr[$i]; 
                        else 
                            $errMsg1 .= $arr[$i]."||"; 
                        }
                    }
                    
                $data['img'] = $req->hinhcu."||".$errMsg1;
                $this->tintuc->updateTintuc($data,$id);
                return redirect()->back()->with('alertsuc','Sửa thành công');
                }
            }
            else
            {
                $this->tintuc->updateTintuc($data,$id);
                return redirect()->back()->with('alertsuc','Sửa thành công');
            }
        }

        if (isset($_POST['xoaEdit']))
        {
            $this->tintuc->destroyFile($id);
            $this->tintuc->updataImg($id);
            return redirect()->back()->with('alertsuc','Xóa hình ảnh thành công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $req)
    {
        if (isset($_POST['btnXoaList']))
        {
            $checked = $req->input('checked',[]);
            foreach ($checked as $id) 
            {
                $this->tintuc->destroyFile($id);
                $this->tintuc->destroyTintuc($id);
            }
            return redirect()->route('tintuc.index')->with('alertsuc','Xóa thành công');
        }

    }
}

resources/views/admin/module/tintucs/tintuc-create.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('tintuc.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Thêm</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">Thông tin khách hàng</h5>
                 
            </div>
            <div class="card-body">
<form action="{{ route('tintuc.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                                <span class="input-group-addon">Tiêu đề</span>
                                            <input value="{{old('title')}}" type="text" name="title" class="form-control" placeholder="Viết tiêu đề ">
                        </div>
                        <div class="col-sm-6">
<span class="input-group-addon">Alias</span>
                                            <input value="{{old('alias')}}" type="text" name="alias" class="form-control" placeholder="Alias">
                        </div>
                    </div>
                    <div class="form-group col-sm-12 row">
                        <div class="col-sm-6">
                            <span class="input-group-addon">Danh mục</span>
                            <select name="category" class="form-control pro-edt-select form-control-primary">
                                <option value="">Hãy chọn thể loại</option>
                                @foreach($dmtt as $ctlg)
                                    @if($ctlg->id_parent >= 1)
                                    <option value="{{$ctlg->id}}">{{$ctlg->name}}</option>
                                    @endif
                                @endforeach
                            </select>
                        </div>
                        <div class="col-sm-6">
                                <span class="input-group-addon ">Hình ảnh đại diện</span>
                                <input type="file" name="photos[]" multiple="" class="btn btn-primary  ">
                        </div>
                    </div>

                    <div class="col-sm-12 form-group">
                         <div class="card-body">
                            <ul class="nav nav-tabs nav-tabs-solid bg-slate border-0 nav-tabs-component rounded">
                                <li class="nav-item"><a href="#colored-rounded-tab1" class="nav-link active" data-toggle="tab">Mô tả ngắn</a></li>
                                <li class="nav-item"><a href="#colored-rounded-tab2" class="nav-link" data-toggle="tab">Nội dung</a></li>
                            </ul>                   
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="colored-rounded-tab1">
                                     <textarea rows="10" id="editor1" name="intro" class="form-control col-md-12 col-xs-12" >{{old('intro')}}</textarea>
                                </div>
                                 <div class="tab-pane fade" id="colored-rounded-tab2">
                                    <textarea rows="10" id="editor2" name="content" class="form-control col-md-12 col-xs-12" >{{old('content')}}</textarea>                            
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="addProduct" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/tintucs/tintuc-edit.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('tintuc.index')}}" class="breadcrumb-item">Danh sách</a>
                <span class="breadcrumb-item active">Sửa</span>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <!-- Content area -->
    <div class="content">
        <!-- Basic card -->
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.btn_sua')}}</h5>
                 
            </div>
            <div class="card-body">
                <form action="{{ route('tintuc.update', ['tintuc' => $tintuc->id]) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    {{ method_field('PUT') }}
                    <div class="col-sm-12 border-bottom row" style="padding-bottom: 5px">
                        <div class="col-sm-6 form-group">
                            <label>Hình ảnh tin tức</label>  
                            @if($tintuc->img == "product_default.jpg")
                                Không có hình ảnh
                            @else
                            <div class="row">
                                @php $arr_img = explode("||",$tintuc->img);@endphp
                                @for($i=0 ; $i<count($arr_img) ; $i++)
                                 <img style="width: 95px;height: 95px;padding: 5px;margin-right: 10px" class="form-control" src="{{ asset('image/'.$arr_img[$i]) }}" alt="">
                                @endfor
                                <button style="height: 35px" class="btn btn-danger" type="submit" title="Xóa ảnh" name="xoaEdit"> <i class="fa fa-trash-o" aria-hidden="true"></i></button>
                                @endif
                            </div>
                           
                        </div>
                        <div class="col-sm-6 form-group">
                            <label>Chọn hình ảnh</label>
                            <input type="file" name="photos[]" multiple="" class="btn btn-primary  ">
                            <input type="hidden" name="hinhcu" value="{{$tintuc->img}}">
                        </div>
                   
                    </div>
                    <div class="col-sm-12 row">
                        <div class="form-group col-sm-6">
                            <span class="input-group-addon">Tiêu đề</span>
                                            <input value="{{old('title',$tintuc->title)}}" type="text" name="title" class="form-control" placeholder="Tên sản phẩm ">
                        </div>
                        <div class="form-group col-sm-6">

                            <span class="input-group-addon">Alias</span>
                                            <input value="{{old('alias',$tintuc->alias)}}" type="text" name="alias" class="form-control" placeholder="Alias">
                        </div>
                    </div>
                    <div class="col-sm-12 row">
                        <div class="form-group col-sm-6">
                            <span class="input-group-addon">Danh mục</span>
                                <select name="category" class="form-control pro-edt-select form-control-primary">
                                        <option value="">Hãy chọn danh mục</option>                       
                                        @foreach($dmtt as $ctlg)
                                        @if($ctlg->id_parent >= 1)
                                            <option value="{{ $ctlg->id }}" {{ (old('category',$tintuc->category) == $ctlg->id) ? 'selected' : '' }}>{{$ctlg->name}}</option>
                                        @endif
                                        @endforeach
                                        
                                </select>
                        </div>
                    </div>
                    <div class="col-sm-12 form-group">
                         <div class="card-body">
                            <ul class="nav nav-tabs nav-tabs-solid bg-slate border-0 nav-tabs-component rounded">
                                <li class="nav-item"><a href="#colored-rounded-tab1" class="nav-link active" data-toggle="tab">Mô tả ngắn</a></li>
                                <li class="nav-item"><a href="#colored-rounded-tab2" class="nav-link" data-toggle="tab">Nội dung</a></li>
                            </ul>                   
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="colored-rounded-tab1">
                                     <textarea rows="10" id="editor1" name="intro" class="form-control col-md-12 col-xs-12" >{{old('intro',$tintuc->intro)}}</textarea>
                                </div>
                                 <div class="tab-pane fade" id="colored-rounded-tab2">
                                    <textarea rows="10" id="editor2" name="content" class="form-control col-md-12 col-xs-12" >{{old('content',$tintuc->content)}}</textarea>                            
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <button name="addTintuc" name="button" type="submit" class="btn btn-primary waves-effect waves-light m-r-10">{{trans('message.btn_luu')}}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /content area -->
</div>
@endsection

resources/views/admin/module/tintucs/tintuc-list.blade.php
@extends('admin.welcome')

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('nhanxet.index')}}" class="breadcrumb-item">Danh sách</a>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('breadcrumb')
<div class="page-header">
    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
        <div class="d-flex">
            <div class="breadcrumb">
                <a href="{{route('index')}}" class="breadcrumb-item"><i class="icon-home2 mr-2"></i> Home</a>
                <a href="{{route('tintuc.index')}}" class="breadcrumb-item">Danh sách</a>
            </div>

            <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
        </div>
    </div>
</div>
@endsection

@section('content')

<div class="content-wrapper">
    @include('admin.blocks.alert')
    <div class="content">
        <div class="card">
            <div class="card-header header-elements-inline">
                <h5 class="card-title">{{trans('message.danhsach_tintuc')}}</h5>
                 
            </div>
            <div class="card-body">
                <div class="product-status-wrap">
                    <div class="form-group">
                         <a  class="btn btn-success" href="{{ route('tintuc.create') }}">{{trans('message.btn_them')}}</a>
                    </div>
                    <form action="" name="listForm" id="listForm" method="post" >
                        {!! csrf_field() !!}
                        <div class="table-responsive-sm form-group">
                            <table class="table table-sm table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <td>
                                            <input type="checkbox" name="checkAll" onClick="checkallClick(checkAll);">
                                        </td>
                                        <th>Mã</th>
                                        <th>Tiêu đề</th>
                                        <th>Thông tin</th>
                                        <th>Thể loại</th>
                                        <th>Cập nhật</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($tintuc as $item)
                                        <tr style="vertical-align: top">
                                            <td >
                                                <input value="{{ $item->id }}" type="checkbox" name="checked[]">         
                                            </td>
                                            <td style="width: 5%">{{$item->id}}</td>
                                            <td style="width: 25%">{{$item->title}}</td>
                                            <td style="width: 45%">{{$item->intro}}</td>
                                            <td style="width: 15%">
                                                    @foreach($dmtt as $ctlg)
                                                        @if($ctlg->id == $item->category)
                                                         <i style="font-style:normal;" data-toggle="tooltip" title="{{$item->category}}">{{$ctlg->name}}</i>
                                                        @endif
                                                    @endforeach
                                            </td>
                                            <td style="width: 10%;text-align: center;">
                                                <a href="{{ route('tintuc.edit', ['tintuc' => $item->id]) }}" data-toggle="tooltip" title="Sửa" class="pd-setting-ed">
                                                    <i class="fa fa-pencil-square-o clear" aria-hidden="true"></i>
                                                </a>
                                            </td>                   
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                        <div class="form-group">
                            {{ method_field('DELETE') }}
                           <button onClick="return xacnhanxoa('Bạn có chắc chắn muốn xóa ?');" id="btnXoaList" name="btnXoaList" type="submit" data-toggle="tooltip" title="Xóa" class="btn btn-danger">
                                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                        </div>
                    
                    </form>
                     {{-- {{$useradmin->links()}} --}}
                </div>
            </div>
        </div>
    </div>
</div> 
@endsection